version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: make test
  lint:
    docker:
    - image: circleci/golang:1.12
    steps:
    - checkout
    - run: make lint
